name: Multiverse-Inventories
main: com.onarandombox.multiverseinventories.MultiverseInventories
version: maven-version-number
author: dumptruckman
depend: ['Multiverse-Core']
softdepend: [MultiInv, WorldInventories]

commands:
  mvinv:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvinfo:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvi:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvim:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvimport:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvlist:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvl:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvreload:
    description: Generic Multiverse-Inventories Command
    usage: /<command>